### ISSUE TITLE
Peers in process of joining are listed in 'Reachability issues'

### ISSUE THREAD

**Issue by vadi2** [petals-infra/health.petals.dev#1]
![image](https://user-images.githubusercontent.com/110988/214054340-1919eff0-6da2-444a-a88e-135ee55b002e.png)

**Comment by borzunov** [comment]
Hi @vadi2,

Thanks for reporting!

This has been fixed in https://github.com/petals-infra/health.petals.dev/commit/00d571cf7266307e2a662a2493fc727e33cf3687.
